apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "messagebroker.fullname" . }}-configmap
  labels:
    {{- include "messagebroker.labels" . | nindent 4 }}
data:
  messagebrokerPort: {{ .Values.messagebroker.config.port | default "3000" | quote }}
  natsUrl: {{ .Values.messagebroker.config.natsClusterUrl | default "nats://nats.default.svc:4222" | quote }}
  withSwagger: {{ .Values.messagebroker.config.withSwagger | default "true" | quote }}
  webUrl: {{ .Values.messagebroker.config.webUrl | default "https://volta-rpc.energyweb.org/" | quote }}
  cacheServerUrl: {{ .Values.messagebroker.config.cacheServerUrl | default "https://identitycache-dev.energyweb.org/" | quote }}
  mbDid: {{ .Values.messagebroker.config.mbDid | quote }}
