apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "messagebroker.fullname" . }}
  labels:
    {{- include "messagebroker.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "messagebroker.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "messagebroker.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "messagebroker.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.messagebroker.config.port | default 3000 }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "messagebroker.fullname" . }}-configmap
                  key: messagebrokerPort
            - name: NATS_JS_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "messagebroker.fullname" . }}-configmap
                  key: natsUrl
            - name: WITH_SWAGGER
              valueFrom:
                configMapKeyRef:
                  name: {{ include "messagebroker.fullname" . }}-configmap
                  key: withSwagger
            - name: WEB3_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "messagebroker.fullname" . }}-configmap
                  key: webUrl
            - name: CACHE_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "messagebroker.fullname" . }}-configmap
                  key: cacheServerUrl
            - name: MB_DID
              valueFrom:
                configMapKeyRef:
                  name: {{ include "messagebroker.fullname" . }}-configmap
                  key: mbDid
            - name: PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "messagebroker.fullname" . }}-secret
                  key: privateKey
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "messagebroker.fullname" . }}-secret
                  key: jwtSecret
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
